### ISSUE TITLE
Thoroughly revise English

### ISSUE THREAD

**Issue by JJ** [NuriaStatgirl/ComparingOptimizationMethods#13]
I can bring somebody from outside, if needed. @aesparcia might help.

**Comment by NuriaStatgirl** [comment]
Sorry, but I think it is not a good idea. 
There is just enaugh people working in this paper. More people means less value for the paper in ANECA's evaluation.

**Comment by JJ** [comment]
OK, we'll just have to do it ourselves.

2015-03-24 14:08 GMT+01:00 Nuria Rico notifications@github.com:

> Sorry, but I think it is not a good idea.
> There is just enaugh people working in this paper. More people means less
> value for the paper in ANECA's evaluation.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NuriaStatgirl/ComparingOptimizationMethods/issues/13#issuecomment-85487119
> .

## 

JJ

**Comment by aesparcia** [comment]
¡Qué miedo! :-S
But fair "enaugh"... ;-)

Date: Tue, 24 Mar 2015 06:38:45 -0700
