### ISSUE TITLE
Explain a lot of stuff

### ISSUE THREAD

**Issue by JJ** [NuriaStatgirl/ComparingOptimizationMethods#5]
`In this paper we focus our attention on the Gompertz-lognormal diffusion pro-
cess [1]. It can be seen as a mixture between a Gompertz-type process [2] and a
lognormal process [3] since the infinitesimal moments that define the Gompertz-
lognormal diffusion process are:`
Well... It's difficult to even start here. Why do we focus our attention on this? Is it the most general one? What is a Gompertz? What is lognormal? Try to address to a general audience.

**Comment by NuriaStatgirl** [comment]
Done

**Comment by JJ** [comment]
You didn't push the result. You have to commit including "closes #5" in the message and them push. Ditto for the other one.
